//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpMgr.Resources.PMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GoalSheetResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoalSheetResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpMgr.Resources.PMS.GoalSheetResource", typeof(GoalSheetResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement.
        /// </summary>
        public static string Achievement {
            get {
                return ResourceManager.GetString("Achievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string AppraiseeSignature {
            get {
                return ResourceManager.GetString("AppraiseeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AppraiseeSignatureDate {
            get {
                return ResourceManager.GetString("AppraiseeSignatureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appraiser Rating.
        /// </summary>
        public static string AppraiserRating {
            get {
                return ResourceManager.GetString("AppraiserRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string AppraiserSignature {
            get {
                return ResourceManager.GetString("AppraiserSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AppraiserSignatureDate {
            get {
                return ResourceManager.GetString("AppraiserSignatureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pick up 2 factors among the 5 Competencies mentioned below.
        /// </summary>
        public static string AreaSelectionNote {
            get {
                return ResourceManager.GetString("AreaSelectionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Appraiser Rating.
        /// </summary>
        public static string AvgAppraiserRating {
            get {
                return ResourceManager.GetString("AvgAppraiserRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Rating.
        /// </summary>
        public static string AvgSelfRating {
            get {
                return ResourceManager.GetString("AvgSelfRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        public static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Areas.
        /// </summary>
        public static string DevelopmentArea {
            get {
                return ResourceManager.GetString("DevelopmentArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years Of Experience.
        /// </summary>
        public static string ExpYr {
            get {
                return ResourceManager.GetString("ExpYr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Rating.
        /// </summary>
        public static string FinalRatingByReviewer {
            get {
                return ResourceManager.GetString("FinalRatingByReviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appraisal Form.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be filled To be filled in by Appraisee first as Self Assessment and then the Appraiser followed by a joint discussion.
        /// </summary>
        public static string HeadingForAppraisee {
            get {
                return ResourceManager.GetString("HeadingForAppraisee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be filled in by Appraisee and Appraiser.
        /// </summary>
        public static string HeadingForAppraiser {
            get {
                return ResourceManager.GetString("HeadingForAppraiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Be Filled By Reviewer.
        /// </summary>
        public static string HeadingForReviewer {
            get {
                return ResourceManager.GetString("HeadingForReviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual Initiative.
        /// </summary>
        public static string IndividualInitiative {
            get {
                return ResourceManager.GetString("IndividualInitiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institutional Support.
        /// </summary>
        public static string InstitutionalSupport {
            get {
                return ResourceManager.GetString("InstitutionalSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPI.
        /// </summary>
        public static string KPI {
            get {
                return ResourceManager.GetString("KPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KRA.
        /// </summary>
        public static string KRA {
            get {
                return ResourceManager.GetString("KRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification.
        /// </summary>
        public static string Qualification {
            get {
                return ResourceManager.GetString("Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting To.
        /// </summary>
        public static string ReportingTo {
            get {
                return ResourceManager.GetString("ReportingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer&apos;s Comment.
        /// </summary>
        public static string ReviewerComment {
            get {
                return ResourceManager.GetString("ReviewerComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You agree / Disagree with the Appraiser&apos;s rating Please give reasons and your comments in the right space.
        /// </summary>
        public static string ReviewerCommentDescription {
            get {
                return ResourceManager.GetString("ReviewerCommentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Of Reviewer.
        /// </summary>
        public static string ReviewerSignature {
            get {
                return ResourceManager.GetString("ReviewerSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ReviewerSignatureDate {
            get {
                return ResourceManager.GetString("ReviewerSignatureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Rating.
        /// </summary>
        public static string SelfRating {
            get {
                return ResourceManager.GetString("SelfRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strengths.
        /// </summary>
        public static string Strengths {
            get {
                return ResourceManager.GetString("Strengths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Appraisal Form.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wightage.
        /// </summary>
        public static string Weightage {
            get {
                return ResourceManager.GetString("Weightage", resourceCulture);
            }
        }
    }
}
