//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpMgr.Resources.User {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpMgr.Resources.User.UserResource", typeof(UserResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddCommand {
            get {
                return ResourceManager.GetString("AddCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admission Date.
        /// </summary>
        public static string AdmissionDate {
            get {
                return ResourceManager.GetString("AdmissionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Contact Number.
        /// </summary>
        public static string AltContactNo {
            get {
                return ResourceManager.GetString("AltContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Alumuni Member.
        /// </summary>
        public static string AnyAlumuniMember {
            get {
                return ResourceManager.GetString("AnyAlumuniMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Group.
        /// </summary>
        public static string BloodGrp {
            get {
                return ResourceManager.GetString("BloodGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Section.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Type.
        /// </summary>
        public static string ClassType {
            get {
                return ResourceManager.GetString("ClassType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        public static string ContactNo {
            get {
                return ResourceManager.GetString("ContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Joining.
        /// </summary>
        public static string DateOfJoining {
            get {
                return ResourceManager.GetString("DateOfJoining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DepartmentId {
            get {
                return ResourceManager.GetString("DepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        public static string DesignationId {
            get {
                return ResourceManager.GetString("DesignationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Qualification.
        /// </summary>
        public static string EducationQualification {
            get {
                return ResourceManager.GetString("EducationQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailId.
        /// </summary>
        public static string EmailId {
            get {
                return ResourceManager.GetString("EmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s Annual Income.
        /// </summary>
        public static string FatherAnnualIncome {
            get {
                return ResourceManager.GetString("FatherAnnualIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s Contact No.
        /// </summary>
        public static string FatherContactNo {
            get {
                return ResourceManager.GetString("FatherContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s Designation.
        /// </summary>
        public static string FatherDesignation {
            get {
                return ResourceManager.GetString("FatherDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s Email Id.
        /// </summary>
        public static string FatherEmailId {
            get {
                return ResourceManager.GetString("FatherEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s Name.
        /// </summary>
        public static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s Occupation.
        /// </summary>
        public static string FatherOccupation {
            get {
                return ResourceManager.GetString("FatherOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s Organisation Name.
        /// </summary>
        public static string FatherOrganisationName {
            get {
                return ResourceManager.GetString("FatherOrganisationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s Qualification.
        /// </summary>
        public static string FatherQualification {
            get {
                return ResourceManager.GetString("FatherQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees Paid For Pvt Tution.
        /// </summary>
        public static string FeesPaidForPvtTution {
            get {
                return ResourceManager.GetString("FeesPaidForPvtTution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FName {
            get {
                return ResourceManager.GetString("FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Contact No.
        /// </summary>
        public static string GuardianContactNo {
            get {
                return ResourceManager.GetString("GuardianContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Email Id.
        /// </summary>
        public static string GuardianEmailId {
            get {
                return ResourceManager.GetString("GuardianEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gurdian Name.
        /// </summary>
        public static string GuardianName {
            get {
                return ResourceManager.GetString("GuardianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Name.
        /// </summary>
        public static string HouseName {
            get {
                return ResourceManager.GetString("HouseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Christian.
        /// </summary>
        public static string IsChristian {
            get {
                return ResourceManager.GetString("IsChristian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Joint Or Nuclear Family.
        /// </summary>
        public static string IsJointOrNuclearFamily {
            get {
                return ResourceManager.GetString("IsJointOrNuclearFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Parent From English Medium.
        /// </summary>
        public static string IsParentFromEngMedium {
            get {
                return ResourceManager.GetString("IsParentFromEngMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Parent Teacher.
        /// </summary>
        public static string IsParentTeacher {
            get {
                return ResourceManager.GetString("IsParentTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LName {
            get {
                return ResourceManager.GetString("LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string MName {
            get {
                return ResourceManager.GetString("MName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s Annual Income.
        /// </summary>
        public static string MotherAnnualInccome {
            get {
                return ResourceManager.GetString("MotherAnnualInccome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s Name.
        /// </summary>
        public static string MotherName {
            get {
                return ResourceManager.GetString("MotherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s Occupation.
        /// </summary>
        public static string MotherOccupation {
            get {
                return ResourceManager.GetString("MotherOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s Organisation Name.
        /// </summary>
        public static string MotherOrganisationName {
            get {
                return ResourceManager.GetString("MotherOrganisationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s Qualification.
        /// </summary>
        public static string MotherQualification {
            get {
                return ResourceManager.GetString("MotherQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Toungue.
        /// </summary>
        public static string MotherToungue {
            get {
                return ResourceManager.GetString("MotherToungue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Tution.
        /// </summary>
        public static string NoOfTution {
            get {
                return ResourceManager.GetString("NoOfTution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a User.
        /// </summary>
        public static string PageHeader {
            get {
                return ResourceManager.GetString("PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a Student.
        /// </summary>
        public static string PageHeaderStudent {
            get {
                return ResourceManager.GetString("PageHeaderStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parmanent Address.
        /// </summary>
        public static string ParmanentAddress {
            get {
                return ResourceManager.GetString("ParmanentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration No.
        /// </summary>
        public static string RegistrationNo {
            get {
                return ResourceManager.GetString("RegistrationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residential Address.
        /// </summary>
        public static string ResidentialAddress {
            get {
                return ResourceManager.GetString("ResidentialAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll No.
        /// </summary>
        public static string RollNo {
            get {
                return ResourceManager.GetString("RollNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Users.
        /// </summary>
        public static string SearchPageHeader {
            get {
                return ResourceManager.GetString("SearchPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchPageTitle {
            get {
                return ResourceManager.GetString("SearchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siblings in Std Or Not.
        /// </summary>
        public static string SiblingInStdOrNot {
            get {
                return ResourceManager.GetString("SiblingInStdOrNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Id.
        /// </summary>
        public static string StaffEmployeeId {
            get {
                return ResourceManager.GetString("StaffEmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student in Private Tution.
        /// </summary>
        public static string StuPrivateTution {
            get {
                return ResourceManager.GetString("StuPrivateTution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectTheyTeach.
        /// </summary>
        public static string SubjectTheyTeach {
            get {
                return ResourceManager.GetString("SubjectTheyTeach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string UserActions {
            get {
                return ResourceManager.GetString("UserActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UserTableName {
            get {
                return ResourceManager.GetString("UserTableName", resourceCulture);
            }
        }
    }
}
