//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpMgr.Resources.Transaction {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Payment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Payment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpMgr.Resources.Transaction.Payment", typeof(Payment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Payment.
        /// </summary>
        public static string BtnPendingPayment {
            get {
                return ResourceManager.GetString("BtnPendingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string CheckboxSelectAll {
            get {
                return ResourceManager.GetString("CheckboxSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted.
        /// </summary>
        public static string GridRowAdjustedAmount {
            get {
                return ResourceManager.GetString("GridRowAdjustedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusting.
        /// </summary>
        public static string GridRowAdjustingAmount {
            get {
                return ResourceManager.GetString("GridRowAdjustingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Paying.
        /// </summary>
        public static string GridRowCurrentlyPaying {
            get {
                return ResourceManager.GetString("GridRowCurrentlyPaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        public static string GridRowDue {
            get {
                return ResourceManager.GetString("GridRowDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string GridRowPaid {
            get {
                return ResourceManager.GetString("GridRowPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string GridRowPaymentButton {
            get {
                return ResourceManager.GetString("GridRowPaymentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string GridRowSubmit {
            get {
                return ResourceManager.GetString("GridRowSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string GridRowTotal {
            get {
                return ResourceManager.GetString("GridRowTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal Approval.
        /// </summary>
        public static string IsPrincipalApproved {
            get {
                return ResourceManager.GetString("IsPrincipalApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Adjustment.
        /// </summary>
        public static string LabelCurrentAdjustment {
            get {
                return ResourceManager.GetString("LabelCurrentAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Paying.
        /// </summary>
        public static string LabelCurrentPaying {
            get {
                return ResourceManager.GetString("LabelCurrentPaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string LabelSubmitAll {
            get {
                return ResourceManager.GetString("LabelSubmitAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Due.
        /// </summary>
        public static string LabelTotalDue {
            get {
                return ResourceManager.GetString("LabelTotalDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment For User.
        /// </summary>
        public static string PageHeader {
            get {
                return ResourceManager.GetString("PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Data to Display.
        /// </summary>
        public static string PaymentSearchNoData {
            get {
                return ResourceManager.GetString("PaymentSearchNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Employee Id.
        /// </summary>
        public static string SearchEmployeeId {
            get {
                return ResourceManager.GetString("SearchEmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Registration No.
        /// </summary>
        public static string SearchRegistrationNo {
            get {
                return ResourceManager.GetString("SearchRegistrationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Staffradio {
            get {
                return ResourceManager.GetString("Staffradio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Studentradio {
            get {
                return ResourceManager.GetString("Studentradio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Details.
        /// </summary>
        public static string TableTransaction {
            get {
                return ResourceManager.GetString("TableTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Payment for User.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string TransactionDueDate {
            get {
                return ResourceManager.GetString("TransactionDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Name.
        /// </summary>
        public static string TransactionName {
            get {
                return ResourceManager.GetString("TransactionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
