//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpMgr.Resources.Transaction {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TransactionRuleSearch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransactionRuleSearch() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpMgr.Resources.Transaction.TransactionRuleSearch", typeof(TransactionRuleSearch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date Increases By.
        /// </summary>
        public static string ColDueIncreasesBy {
            get {
                return ResourceManager.GetString("ColDueIncreasesBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Due After Days.
        /// </summary>
        public static string ColFirstDueAfterDays {
            get {
                return ResourceManager.GetString("ColFirstDueAfterDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty Amount.
        /// </summary>
        public static string ColPenaltyAmt {
            get {
                return ResourceManager.GetString("ColPenaltyAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string ColRuleAmount {
            get {
                return ResourceManager.GetString("ColRuleAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Name.
        /// </summary>
        public static string ColRuleName {
            get {
                return ResourceManager.GetString("ColRuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty Calc In.
        /// </summary>
        public static string ColRulePenaltyCalcIn {
            get {
                return ResourceManager.GetString("ColRulePenaltyCalcIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees Rules.
        /// </summary>
        public static string PageHeader {
            get {
                return ResourceManager.GetString("PageHeader", resourceCulture);
            }
        }
    }
}
