//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpMgr.Resources.Transaction {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TransactionSearch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransactionSearch() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpMgr.Resources.Transaction.TransactionSearch", typeof(TransactionSearch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Id.
        /// </summary>
        public static string Col1 {
            get {
                return ResourceManager.GetString("Col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Col10 {
            get {
                return ResourceManager.GetString("Col10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Col11 {
            get {
                return ResourceManager.GetString("Col11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Penalty.
        /// </summary>
        public static string Col12 {
            get {
                return ResourceManager.GetString("Col12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        public static string Col13 {
            get {
                return ResourceManager.GetString("Col13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string Col14 {
            get {
                return ResourceManager.GetString("Col14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Col2 {
            get {
                return ResourceManager.GetString("Col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Col3 {
            get {
                return ResourceManager.GetString("Col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Id.
        /// </summary>
        public static string Col4 {
            get {
                return ResourceManager.GetString("Col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Col5 {
            get {
                return ResourceManager.GetString("Col5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed On.
        /// </summary>
        public static string Col6 {
            get {
                return ResourceManager.GetString("Col6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amt.
        /// </summary>
        public static string Col7 {
            get {
                return ResourceManager.GetString("Col7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Amt.
        /// </summary>
        public static string Col8 {
            get {
                return ResourceManager.GetString("Col8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Amt.
        /// </summary>
        public static string Col9 {
            get {
                return ResourceManager.GetString("Col9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted Amt.
        /// </summary>
        public static string ColAdjstAmt {
            get {
                return ResourceManager.GetString("ColAdjstAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Id.
        /// </summary>
        public static string EmployeeId {
            get {
                return ResourceManager.GetString("EmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction From.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data to display.
        /// </summary>
        public static string NoDataMsg {
            get {
                return ResourceManager.GetString("NoDataMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string PaymentLinkText {
            get {
                return ResourceManager.GetString("PaymentLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration No.
        /// </summary>
        public static string RegNumber {
            get {
                return ResourceManager.GetString("RegNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Section.
        /// </summary>
        public static string StandardSection {
            get {
                return ResourceManager.GetString("StandardSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction To.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Transaction.
        /// </summary>
        public static string TransSearchPageHeader {
            get {
                return ResourceManager.GetString("TransSearchPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        public static string TransType {
            get {
                return ResourceManager.GetString("TransType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string UserFName {
            get {
                return ResourceManager.GetString("UserFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string UserLName {
            get {
                return ResourceManager.GetString("UserLName", resourceCulture);
            }
        }
    }
}
